<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SynthML" nsURI="https://github.com/TNO/SynthML/" nsPrefix="SynthML">
  <eClassifiers xsi:type="ecore:EClass" name="FormalElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effects" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_RedefinableElement"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//RedefinableElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atomic" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalControlFlow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outgoingGuard" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_ControlFlow" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//ControlFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalCallBehaviorAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" ordered="false"
        unique="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_CallBehaviorAction"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//CallBehaviorAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//FormalConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormalConstraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Constraint" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynthesisPrecondition" eSuperTypes="#//FormalConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="UsagePrecondition" eSuperTypes="#//FormalConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Postcondition" eSuperTypes="#//FormalConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormalActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Activity" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
