= UML Semantics

This documents describes the subset of UML used by Poka Yoke, with the semantics in the Poka Yoke workflows.
In addition, it describes the stereotypes introduced by Poka Yoke, including their properties.

== Type
Types define the kind of elements that a Poka Yoke model supports. These are boolean, (ranged) integers, enumeration and user-defined data types. 

== Class
A class represents a container of behaviors. An active class (and an active object, more in general) starts its classifier behavior as a direct consequence of its creation. When the classifier behavior terminates, the class instantiation is terminated.  
Only active classes are supported. 

== DataType
A data type is an element that defines data values, usually in the form of owned attributes (properties).
Data types are used to represent primitive types or user-defined data types. 
In contrast to classes, data types are identified only by their values, not by reference. 
If two data types have the same attributes' values, they are considered identical (identity by value, not by reference).

== Property (Attribute)
A property is a structural feature of its classifier, defined as an owned attribute. It relates an instance of the classifier to a set of values of the type of the attribute. It can only be of one of the supported types. 

== Behavior
A behavior is a specification of how its context (usually, a classifier) changes state over time. 
They are executed either by invocation (see <<Call Behavior Action>>) or by the creation of an active object (e.g. an active class).
A _classifier behavior_ represents the primary behavior of a classifier, describing the behavior of an instance of the owning classifier. 

== Activity
An activity is a behavior, defined as a sequence of subordinate units (actions, or calls to other behaviors). 
The flow of its execution is modeled as activity nodes connected through activity edges, similarly to a graph where nodes are connected via edges. 
An _abstract_ activity identifies an activity to be synthesised, that contains preconditions, i.e. the conditions that must hold before the execution of the activity; postconditions, i.e. the effects that the activity will have on the model properties; and occurrence constraints, that limits the number of calls of a given opaque behavior. 
A _concrete_ activity represents a series of activity nodes and activity edges designed by the user.

== Activity Edge (Control Flow)
An activity edge (also denoted control flow) connects two UML elements in the execution flow, and these represent the transitions (edges) of the activity. Edges can be taken if and only if their guards -- which are state predicates -- hold true. 

== Activity Node
Activity nodes define the locations of a series of actions, similarly to nodes in a graph. 
Activity nodes can be of three main kinds: 

* Call behavior action node, which execute an action by calling a given opaque behavior (see <<Call Behavior Action>>).
* Opaque action node, representing an action to be executed with guards and effects (see <<Opaque Action>>).
* Decision Node, which include six different sub-kinds:
** Initial node: determines the starting point of an activity;
** Final node: determines the ending point of an activity;
** Fork node: represents the entry point of two or more concurrent paths;
** Join node: represents the exit point of two or more concurrent paths;
** Decision node: represents the beginning of a non-deterministic choice between two or more paths. Recall that the subsequent edges are equipped with guards, that allow or prevent certain paths from being taken;
** Merge node: represents the end of a non-deterministic choice between two or more paths.

== Call Behavior Action
A call behavior action effectively calls the execution of a given opaque behavior. It is equipped with guards and effects, to abstract the call to the behavior without entering the actual execution of it: this avoids a possibly recursive call to a series of sub-behaviors, and instead only the guards and effects of the call are considered. During a simulation run, when encountering a Call Behavior Action that has guards and effects, its activity, including any sub-activities, is ignored, but instead the action is treated as an Opaque Action with a guard and effect. 
In short, guards and effects of a call behavior action shadow the call to the behavior by something more abstract. 

== Opaque Expression 
Opaque expressions constitute the body of a constraint, e.g. a precondition or a postcondition. These usually represent a state predicate over a subset of the model properties. 

== Opaque Behavior
Opaque behaviors model _actions_ to be performed in activities. Equipped with guards -- state predicates --  and effects -- state updates -- over the UML model properties. 
Actions can be 

* Deterministic, if it has at most one effect; nondeterministic otherwise. If nondeterministic, one of the possible outputs is chosen arbitrarily and executed.  
* Atomic, if no other actions can be performed during its execution; non-atomic otherwise. If non-atomic, other actions can be performed between the start and the end of it -- the start and end events are modeled as atomic. The effects of a non-atomic action are applied when the action ends. 

== Opaque Action
An opaque action represents an ``inlined'' opaque behavior. 
An opaque behavior can only be called, whereas opaque actions represent the actual action to be performed. Opaque behaviors can be called in multiple places, whilst opaque actions needs to be redefined for every single use.  

== Constraint
A constraint is an element which represents some condition, restriction or assertion related to its owning element. 
Constraints are usually specified by an <<opaque expression>> containing a state predicate. 
Constraints are used for several purposes: pre and postconditions of an abstract activity, 
state invariants, 
action exclusion invariant. 

== Occurrence Constraint
An occurrence constraint limits the number of times a given element (denoted _constrained_ element) can be called by the constraint's owner. 

== Poka Yoke stereotype
Poka Yoke stereotypes are an extension to UML constructs, that equips UML elements with formal modeling components. In practical terms, it gives the possibility to specify guards and effects (when appropriate) and to define the atomicity of a UML element. We define four different stereotypes: 

* Formal Element stereotype, that adds guards, effects and the definition of atomicity; it is applied to opaque behaviors, opaque actions, call behavior actions.
* Control Flow stereotype, that adds only guards; it is applied to control flows. 
* Property stereotype, that allows the  definition of type and default value; it is applied to properties.
* Primitive Type stereotype, that allows the definition of type, along with minimum and maximum values; it is applied to primitive types. 
